project:
    
  type: website
  output-dir: docs 
  title: "Shahram Dehghan Jabarabadi"
  resources:
    - "googlea001f7a2c08a32a0.html"
    - "robots.txt"
    - "sitemap.xml"
    - "favicon.svg"


website:
  
  site-url: "https://shahram-dehghan-j.github.io/"
  favicon: favicon.svg
  
  navbar:
    title: false   # hides the title from the navbar
    left:
      - text: 'Home'
        href: index.qmd
      - text: 'Curriculum Vitae'
        menu:
          - text: 'Career'
            href: about/career.qmd
          - text: 'Education'
            href: about/education.qmd
          - text: 'Teaching'
            href: about/teaching.qmd
          - text: 'Awards'
            href: about/awards.qmd
      - text: 'Research'
        menu:
          - text: 'Publications'
            href: research/publications.qmd
          - text: 'Interests'
            href: research/interests.qmd
          - text: 'Indices'
            href: research/indices.qmd
      - text: 'Open Science'
        menu:
          - text: "Data"
            href: tutorial/dataPage.qmd
          - text: "Python"
            href: tutorial/pythonPage.qmd
          - text: "R"
            href: tutorial/rPage.qmd
          - text: "LaTeX"
            href: tutorial/latexPage.qmd
   
    right:
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=W_Qsf4MAAAAJ&hl=it&oi=ao
      - text: '<img src="/ORCID_iD_icon.svg" alt="ORCID" style="height:20px; vertical-align:middle;">'
        href: https://orcid.org/0009-0008-4627-7554
      - icon: linkedin
        href: https://www.linkedin.com/in/shahram-dehghan-jabarabadi
      - icon: envelope-at
        href: mailto:shahram.deghan.j@icloud.com
 

  page-footer:
    left: 
      - text: '🇮🇷 - 🇮🇹 <br> Copyright © 2024. <a href="https://www.wipo.int/copyright/en/" target="_blank">Legal Info</a>'
    right:
      - text: "<strong>© <script>document.write(new Date().getFullYear());</script> Shahram Dehghan Jabarabadi</strong>"
    center: 
      - text: "<i class='bi bi-geo-alt me-2'></i> Padua, Italy"


format:
  html:
    theme: journal
    canonical-url: true
    css: css/styles.css
    html-meta:
      google-site-verification: "googlea001f7a2c08a32a0"
      description: "Personal academic website of Shahram Dehghan Jabarabadi, Postdoctoral Research Fellow at the University of Padua. Specializing in Econometrics, Textual Analysis, and Quantitative Finance with expertise in Time Series, Risk Management (VaR/ES/GARCH), and NLP (Sentiment/Topic Modeling). Research focuses on volatility, ESG indicators, and text-based analysis of economic systems."
      keywords: "Shahram Dehghan Jabarabadi, Shahram Dehghan, Shahram, Dehghan, Jabarabadi, Economics, Econometrics, Textual Analysis, Quantitative Finance, Time Series Analysis, Risk Management, Natural Language Processing, NLP, Statistical Methods, GARCH, VaR, ES, ESG Integration, Volatility Analysis, Python, R,  University of Salerno, University of Padua, Postdoctoral Fellow, Research, Ph.D., Docotrate, Dr., شهرام دهقان, شهرام دهقان جبارآبادی, جبارآبادی, جبارابادی, دادههای متنی, تحلیل ریسک, بازارهای مالی, اقتصاد, اقتصادسنجی, روشهای آماری"
    include-in-header:
      - text: |
          <!-- Font Awesome -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
          <!-- Academicons -->
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons/css/academicons.min.css">
