---
title: "Education"
format: html
---

<div class="rule-gradient"></div>
# <i class="bi bi-people"></i> Postdoctorate and Research Fellowship

**Research Fellow** &nbsp;&nbsp;&nbsp;&nbsp; May 2025 - present <br>
Department of Economics and Management (dSEA), University of Padova, Italy <br><br>
**PROJECTS/**<br>
│<br>
├── PRIN–LEXECON/ <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── `May 2026 - June 2026` <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Contratto per Prestazione di Lavoro Autonomo</small> <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Supervision:</small> Prof. Gianfranco Tusset<br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── *Entitled: "A transnational and diachronic study of treatises and textbooks of Economics."* <br>
│<br>
├── PNRR P9–GRINS Growing Resilient/ <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── `August 2025 - April 2026` <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Contratto per Prestazione di Lavoro Autonomo</small> <br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Supervision:</small> Prof.ssa Paola Valbonessi<br>
│&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── *Entitled: "Sustainable procurement and CO2 reduction."* <br>
│<br>
└── PNRR–CHANGE/ <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── `July 2026 - present` 🟢 <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── `May 2025 - September 2025` <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Contratto per Prestazione di Lavoro Autonomo</small> <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;├── <small>Supervision:</small> Prof.ssa Alessia Russo<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── *Entitled: "CHAllenges in National Governance of Environment."* <br><br>

---

**Postdoctoral Research Fellow** &nbsp;&nbsp;&nbsp;&nbsp; May 2024 - May 2025 <br>
Department of Economics and Management (dSEA), University of Padova, Italy <br>
PRIN–LEXECON <br>
Type of Contract: Contratto di Ricerca <br>
<small>Supervision:</small> Prof. Gianfranco Tusset<br>
*Entitled: "A transnational and diachronic study of treatises and textbooks of Economics. Intra- and interlingual corpus-driven and corpus-based analysis with a focus on lexicon and argumentation."* <br><br>



<div class="rule-gradient"></div>
# <i class="bi bi-award"></i> Degrees

**Doctorate (Ph.D.)** &nbsp;&nbsp;&nbsp;&nbsp; October 2020 – July 2024 <br>
Economics and Policy Analysis of Markets and Firms (curriculum: *Statistical Methods*) <br>
<small>Supervision:</small> Prof. Vincenzo Candila<br>
Thesis: *"Essays on Financial Markets: Statistical Methods, Textual Analysis, and ESG Integration."* <br>
Department of Economics and Statistics <br>
University of Salerno (Salerno, Italy) <br><br>

**Master (M.A.)** &nbsp;&nbsp;&nbsp;&nbsp; September 2015 – May 2017 <br>
Economics (curriculum: *Econometrics*) <br>
<small>Supervision:</small> Prof. Shahram Fattahi<br>
<small>Co-Supervision:</small> Prof. Kiomars Sohaili<br>
Thesis: *"Examinations of Contagion in Financial markets in Iran Using a Combination of Ornstein Uhlenbeck Process and Wavelet Method."* <br>
Department of Economics <br>
Razi University (Kermanshah, Iran) <br><br>

**Bachelor (B.A.)** &nbsp;&nbsp;&nbsp;&nbsp; September 2008 – May 2012 <br>
Economics <br>
Thesis: *"Effect of financial Development and Trade Liberalization on Economic Growth."* <br>
Department of Economics <br>
Payame Noor University (Kermanshah, Iran) <br><br>

**Pre-University Degree** &nbsp;&nbsp;&nbsp;&nbsp; September 2005 - July 2006 <br>
Mathematics and Physics <br>
General and intermediate theories of Mathematics and Physics <br>
Ali Ebne Abitaleb Pre-university (Kermanshah, Iran) <br><br>

**Diploma Degree** &nbsp;&nbsp;&nbsp;&nbsp; 2002 - July 2005 <br>
Mathematics and Physics <br>
General theories of Mathematics and Physics <br>
Loghmane Hakim High school (Kermanshah, Iran) <br><br>

<div class="rule-gradient"></div>
# <i class="bi bi-globe"></i> Visiting Research Programs

**Visiting Research Program (Ph.D.)** &nbsp;&nbsp;&nbsp;&nbsp; August 2022 – November 2022 <br>
**Focus:** Textual Analysis and Sustainability Topics. <br>
Research entitled: *"A Novel ESG Indicator from Textual Data: Construction, Evaluation, and Risk Management Applications."* <br>
Department of Economics <br>
Justus Liebig University Giessen (Giessen, Germany) <br><br>

<div class="rule-gradient"></div>
# <i class="bi bi-mortarboard"></i> Postgraduate Courses and Certifications

**Financial Time Series and High-Frequency Econometrics** &nbsp;&nbsp;&nbsp;&nbsp; July 2023 <br>
*Issued by:* SIDE (Società Italiana di Econometria) <br>
Perugia, Italy <br><br>

**Oxford Summer School in Economic Networks** &nbsp;&nbsp;&nbsp;&nbsp; June 2021 <br>
*Issued by:* Institute for New Economic Thinking at the Oxford Martin School (INET Oxford) <br>
[vertual], UK <br><br>
	
**Spatial Econometrics Advanced** &nbsp;&nbsp;&nbsp;&nbsp; June 2021 <br>
*Issued by:* Spatial Econometrics Association <br>
[vertual], Italy <br><br>

<div class="rule-gradient"></div>

