---
title: "Curriculum Vitae and Awards"
format: html
---

<div class="rule-gradient"></div>
 
# <i class="bi bi-briefcase"></i> Timeline: Professional Experience

```{=html}
<div class="timeline">
<div class="timeline-item">
<div class="timeline-date">May 2025 – September 2026</div>
<div class="timeline-info">
<div class="timeline-title">Research Fellow</div>
<div class="timeline-org">University of Padova, Dept. of Economics and Management, Padova, Italy.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties">
  <ul>
    <li>Textual data analysis and quantifications;</li>
    <li>Econometrics timeseries analysis;</li>
    <li>Cooperation in meeting and discussions;</li>
    <li>Teaching and Publication;</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">May 2024 – May 2025</div>
<div class="timeline-info">
<div class="timeline-title">Postdoctoral Research Fellow (CHANGE / LEXECON)</div>
<div class="timeline-org">University of Padova, Dept. of Economics and Management, Padova, Italy.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties"><ul>
    <li>Textual data analysis and quantifications for the pre-defined project;</li>
    <li>Econometrics timeseries analysis;</li>
    <li>Cooperation in meeting and discussions;</li>
    <li>Teaching;</li>
    <li>Publication;</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">August 2022 – November 2022</div>
<div class="timeline-info">
<div class="timeline-title">Visiting Research Activity (Ph.D.)</div>
<div class="timeline-org">Department of Economics, Justus Liebig University Giessen, Giessen, Germany.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties">
  <ul>
    <li>Training: Textual data analysis and quantifications techniques;</li>
    <li>Training: Application of Python in Text mining and econometrics analysis;</li>
    <li>Publication;</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">October 2020 – July 2024</div>
<div class="timeline-info">
<div class="timeline-title">Doctorate (Ph.D.) Degree</div>
<div class="timeline-org">University of Salerno, Dept. of Economics and Statistics, Salerno, Italy.</div>
<div class="timeline-duties">
  <ul>
    <li>Education Period.</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">July 2017 – June 2020</div>
<div class="timeline-info">
<div class="timeline-title">Research Assistant</div>
<div class="timeline-org">Maazhin Group (Economist), Kermanshah, Iran.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties">
  <ul>
    <li>Gather data of the public project;</li>
    <li>Estimate the econometric and statistics models regarding the project;</li>
    <li>Primary interpretation the estimation;</li>
    <li>Linking between the accountant department and the research group.</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">September 2015 – May 2017</div>
<div class="timeline-info">
<div class="timeline-title">Master (M.A.) Degree</div>
<div class="timeline-org">Razi University, Kermanshah, Iran.</div>
<div class="timeline-duties">
  <ul>
    <li>Education Period.</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">March 2014 – April 2015</div>
<div class="timeline-info">
<div class="timeline-title">Heavy Truck Controller</div>
<div class="timeline-org">Giti Afrooz Factory, Kermanshah, Iran.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties">
  <ul>
    <li>Control the output and input of the stone broken machine;</li>
    <li>Control the number of time heavy trucks load and unload;</li>
    <li>Prepare the report for the accountant department at the end of day.</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">March 2013 – December 2013</div>
<div class="timeline-info">
<div class="timeline-title">CO2 Welder</div>
<div class="timeline-org">Novin Sazeh Company, Kermanshah, Iran.</div>
<div class="timeline-org">Duties and Responsibilities:</div>
<div class="timeline-duties">
  <ul>
    <li>Welding the huge part of the building-skeleton By MAG technology;</li>
  </ul>
</div>
</div>
</div>

<div class="timeline-item">
<div class="timeline-date">September 2008 – May 2012</div>
<div class="timeline-info">
<div class="timeline-title">Bachelor Degree</div>
<div class="timeline-org">Payame Noor University, Kermanshah, Iran.</div>
<div class="timeline-duties">
  <ul>
    <li>Education Period.</li>
  </ul>
</div>
</div>
</div>

</div>

<div class="rule-gradient"></div>

# <i class="bi bi-trophy"></i> Research Grants and Fellowships

- **Research Fellow (Borsa di Ricerca)**
    * **Project:** "Survey on foreign workers in the domestic/care sector" RIF. 2025BR26.
    * **Institution:** Department of Economics and Management, University of Padova, Italy.
    * **Duration:** January 2026 – Present.

- **Research Fellow (Borsa di Ricerca)**
    * **Project:** PNRR P9-GRINS Growing Resilient.
    * **Institution:** Department of Economics and Management, University of Padova, Italy.
    * **Duration:** August 2025 – December 2025.

- **Research Grant (Co.co.co)**
    * **Project:** PNRR-CHANGE (CHAllenges in National Governance of Environment).
    * **Institution:** Department of Economics and Management, University of Padova, Italy.
    * **Duration:** August 2025 – December 2025.

- **Postdoctoral Research Grant**
    * **Project:** PRIN-LEXECON.
    * **Institution:** Department of Economics and Management, University of Padova, Italy.
    * **Duration:** May 2024 – May 2025.

<div class="rule-gradient"></div>
# <i class="bi bi-mortarboard"></i> Doctoral Scholarship

- **Ph.D. in Economics and Policy Analysis of Markets and Firms**
    * **Curriculum:** Statistical Methods.
    * **Institution:** Department of Economics and Statistics, University of Salerno, Italy.
    * **Duration:** October 2020 – January 2024.
  

<div class="rule-gradient"></div>